name: ci/cd by guitar

on:
  push:
    branches:
      - 'main'

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: 🔨 Build Project
      run: |
        yarn
        yarn build

    - name: automated test
      run: |
        yarn cypress run
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: -D6bgR2Q4W)5df
        local-dir: dist/
        server-dir: domains/sabaiphone-admin.com/public_html/
        timeout: 999999
  connect-to-server:
    needs: web-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Noti to discord
        run: |
          run: |
          curl --location 'https://discord.com/api/webhooks/1149562834238320661/Q-h-xQWjlv9rY8ROaZpj-KmXNahENxdAeLOAm_vDfYLwXGTDR13FisPx039pwBift5I-' \
          --header 'Content-Type: application/json' \
          --header 'Cookie: __cfruid=76888d7ffd99ee8b6171603af5dc4ee125f2a12c-1694110508; __dcfduid=7a4fc2c24daa11eebe841a2eb2a836be; __sdcfduid=7a4fc2c24daa11eebe841a2eb2a836be2c3a4bae4035262740391e0b0c57b5f5539a4c6baf13902223f7917ae86296d2; _cfuvid=byAQ_tNTwGpgfHuXBAGwC8lzUrItMtv1_EoTDduv44g-1694110508816-0-604800000' \
          --data '{
              "content": "[งาน stock สบายโฟน] \nDeploy success !! :guitar:\n${{ github.event.head_commit.author.name }} : ${{ github.event.head_commit.message }}"
          }'
  dis-hui:
    needs: web-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Noti to discord
        run: |
          run: |
          curl --location 'https://discord.com/api/webhooks/1147789907532714068/UCF5wDKYRIBKEyAf1QPmVYEY52qA30Sonfi3VSxXTwcCSRdEscyrrKVP1AM9luiAgtu8' \
          --header 'Content-Type: application/json' \
          --header 'Cookie: __cfruid=76888d7ffd99ee8b6171603af5dc4ee125f2a12c-1694110508; __dcfduid=7a4fc2c24daa11eebe841a2eb2a836be; __sdcfduid=7a4fc2c24daa11eebe841a2eb2a836be2c3a4bae4035262740391e0b0c57b5f5539a4c6baf13902223f7917ae86296d2; _cfuvid=byAQ_tNTwGpgfHuXBAGwC8lzUrItMtv1_EoTDduv44g-1694110508816-0-604800000' \
          --data '{
              "content": "[งาน stock สบายโฟน] \nDeploy success !! :guitar:\n${{ github.event.head_commit.author.name }} : ${{ github.event.head_commit.message }}"
          }'
