name: ci/cd by guitar

on:
  push:
    branches:
      - 'main'

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: 🔨 Build Project
      run: |
        yarn
        yarn build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: -D6bgR2Q4W)5df
        local-dir: dist/
        server-dir: domains/sabaiphone-admin.com/public_html/
  connect-to-server:
    needs: web-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Noti to discord
        run: |
          curl --location '${{ secrets.URL }}/noti.php' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "commit": "\n```${{ github.event.head_commit.message }}```"
          }'
